language: cpp
dist: xenial
sudo: required
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  exclude:
    - os: osx
      compiler: gcc # Don't do a gcc build on OSX
cache: apt
install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then .travis/setup_linux.sh ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then .travis/setup_osx.sh ; fi
script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] ; then cmake -DCMAKE_PREFIX_PATH=/opt/qt54/lib/cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Debug . && make -j4 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_BUILD_TYPE=Release . && make -j4 ; fi
  - make check
